language: node_js

node_js:
  - node
  - 8

cache:
  directories:
    - "node_modules"

install:
    - yarn

script:
    - yarn webpack:version
    - yarn patternlab:build

branches:
  only:
    - master
    - latest
