language: node_js

node_js:
  - lts/*

cache:
  directories:
    - "node_modules"

env:
  - TESTFOLDER=test-examples/sample-project-simple
#  - TESTFOLDER=test-samples/sample-project-simple
#  - TESTFOLDER=test-samples/sample-project-simple
#  - TESTFOLDER=test-samples/sample-project-simple

install:
    - yarn

script:
    - yarn webpack:version
    - cp -a /$TESTFOLDER/. /source/
    - yarn patternlab:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local-dir: public
  on:
    branch: master

branches:
  only:
    - master
    - latest
